### ISSUE TITLE
有接受任務，但是在其他任務頁面返回到主畫面後，任務資訊清單顯示進行中的任務數量錯誤

### ISSUE THREAD

**Issue by skysumbra** [lawvs/poi-plugin-quest-2#1]
**poi 版本 / poi version:**
10.6.0

**操作系统 / OS:**
Win 10

**插件版本 / Plugin version:**
0.3.2

**你遇到了什么样的问题 / The problem you've met:**
有接受任務，但是在其他任務頁面返回到主畫面後，任務資訊清單顯示進行中的任務數量錯誤

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
1.啟用外掛的同步功能和選擇全部與進行中狀態
2.接下來遊戲內接下各種不同天數的任務，例如分別是日、周、月，請接滿不同時間2個以上，最大數量5個
3.遊戲內任務選單切換到進行中
4.遊戲內任務選單切換到其他的時間分類，例如日、周、月
5.遊戲內回到母港(左上)
6.觀察任務外掛顯示的清單 -----> 顯示的清單數量錯誤，不是進行中頁面的任務數量

**目前解決方法**
遊戲內任務接好後，切換到進行中任務頁面，再點左上母港回到主畫面

**Comment by lawvs** [comment]
由於這個問題過於久遠，我就關閉這個問題，但如果這個問題還能復現，歡迎您重新打開或創建新問題。
