### ISSUE TITLE
F119砲熕兵装の整備 任務說明錯誤

### ISSUE THREAD

**Issue by nicholaspeng86** [lawvs/poi-plugin-quest-2#106]
**poi 版本 / poi version: 11.0.0-beta.5

**操作系统 / OS: Windows 10

**插件版本 / Plugin version: 0.12.7

**你遇到了什么样的问题 / The problem you've met: 任務F119 "砲熕兵装の整備" 說明不正確

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related: 

插件顯示:
![image](https://github.com/lawvs/poi-plugin-quest-2/assets/63907434/7d8136e1-8b61-4fe0-a9ce-557646dd36f4)
正確說明:
![螢幕擷取畫面 2024-02-19 133357](https://github.com/lawvs/poi-plugin-quest-2/assets/63907434/30f7b928-291c-42da-8885-a104734202fd)

**Comment by lawvs** [comment]
感謝您的反饋，我已經將這個問題反饋給上游！

**Comment by lawvs** [comment]
上遊已經修複了這個問題
