### ISSUE TITLE
Fw3和Fw4两个周常工厂算在单次任务里了，应该是周常任务

### ISSUE THREAD

**Issue by GiantGentleman** [lawvs/poi-plugin-quest-2#108]
![image](https://github.com/lawvs/poi-plugin-quest-2/assets/63355063/604934dd-577c-4306-bb4f-480558a26959)

**Comment by lawvs** [comment]
非常感谢你的反馈！这个问题会在刚刚发布的 `v0.12.9` 版本中得到修复，同时还有另外一些分类不正确的任务也会一起修复。

出现这个问题的原因是由于之前判断任务分类是根据该任务的描述是否包含特定信息（比如任务的描述中包含`周常`就把它归到周常任务），这个方法显然既不优雅也不准确。

不过，去年社区采用了新的任务编号，我们可以准确有效地从编号判断任务的类别了（所有像`Aw1`/`Bw2`等等形如`Xw00`的任务都算周常），这次修复就是使用了新的任务编号判断任务的类别。

再次感谢使用该插件！
