### ISSUE TITLE
Cy12 春です！「春雨」、演習しますっ！ 任務說明錯誤

### ISSUE THREAD

**Issue by Amemiyasora** [lawvs/poi-plugin-quest-2#115]
**poi 版本 / poi version:** 11.0.0-beta.6

**操作系统 / OS:**Windows 10

**插件版本 / Plugin version:**0.12.10

**你遇到了什么样的问题 / The problem you've met:** Cy12 春です！「春雨」、演習しますっ！ 任務說明錯誤 

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://github.com/lawvs/poi-plugin-quest-2/assets/28768821/e23415e8-ff22-46ef-a06f-c2c880f5baca)
![image](https://github.com/lawvs/poi-plugin-quest-2/assets/28768821/b87c3555-5d79-4596-a273-c937a7fedaf9)
您好，该任务简体中文说明中的村雨误显示成了春雨，可能对做任务的人有一定影响

**Comment by lawvs** [comment]
这是一个上游的数据错误，我已经在 kcwiki 中修复了这个错误，插件数据也会在 0.12.2 中得到更新（另外 11周年記念任務 也更新上了），非常感谢你的反馈！

<img width="1074" alt="Screenshot 2024-04-25 at 10 11 44" src="https://github.com/lawvs/poi-plugin-quest-2/assets/18554747/c13ff7b9-5413-4869-b91a-094a6d595bf2">

**Comment by Amemiyasora** [comment]
感謝您的工作
