### ISSUE TITLE
空白處增加完成項目計數統計

### ISSUE THREAD

**Issue by skysumbra** [lawvs/poi-plugin-quest-2#2]
**poi 版本 / poi version:**
10.6.0

**操作系统 / OS:**
win 10

**插件版本 / Plugin version:**
0.3.2

**功能的详细描述 / Details on the feature:**
希望在空白位置上增加增加完成計數的統計，目前內建的功能的任務提示的完成項目已經沒有支援新的任務名

**Comment by lawvs** [comment]
統計任務完成數按目前情況下很難實現，有幾點原因

- 很多任務具體完成條件至今尚不明確。比如很多出擊任務都會有艦種要求，而遊戲中又包含了大量特殊艦種（輕巡/練巡/雷巡）（戰艦/航戰），攻略組也難以一一確認各種變體艦種是否滿足條件
- 如果要實現次功能，必須單獨處理大量任務，而這些任務很多都是單次任務，開發的收益並不高，poi 官方也只是簡單處理了使用頻率高的每日任務
- 開發者最近有點忙，沒有大量的時間用於更新

新的任務插件主要目的還是作為舊插件任務數據缺失的替代，讓大家能夠及時看到新任務的任務描述，沒有計劃做很多很酷的新功能（海域關卡出擊統計是有點想做的），沒能幫上你的忙非常抱歉

**Comment by skysumbra** [comment]
如果用這個任務外掛來舉例，請問如何參考和修改？
雖然沒有經驗，就嘗試空閒時來學習

**Comment by lawvs** [comment]
如果你有一定的編碼基礎，可以嘗試學習 現代 JavaScript/ES6，然後試試 [React](https://reactjs.org/) 這個前端框架，如果有其他疑問也歡迎用郵件聯繫我
