### ISSUE TITLE
空白處增加選擇獎勵的提示

### ISSUE THREAD

**Issue by skysumbra** [lawvs/poi-plugin-quest-2#3]
**poi 版本 / poi version:**
10.6.0
**操作系统 / OS:**
win10
**插件版本 / Plugin version:**
0.3.2
**功能的详细描述 / Details on the feature:**
有選擇獎勵的任務，能在共白處直接提示要選擇的獎勵敘述(目前，滑鼠移動該任務，才會有文字提示)

**Comment by lawvs** [comment]
樣式已更新

<img width="807" alt="Screen Shot 2021-07-18 at 03 53 20" src="https://user-images.githubusercontent.com/18554747/126048029-bb28f0d0-c70e-4797-873b-4f2320ef3de2.png">

See https://github.com/lawvs/poi-plugin-quest-2/commit/485cf16fe0739d7a2a67e0209f21579f04390275
