### ISSUE TITLE
安裝完任務信息2後無法在插件中找到，且無法運作。

### ISSUE THREAD

**Issue by darkwang2003** [lawvs/poi-plugin-quest-2#37]
poi 版本 / poi version: 10.9.2

操作系统 / OS: win10

插件版本 / Plugin version: 0.9.14

功能的详细描述 / Details on the feature: 
安裝後常常停止運作，有時候又會正常運作，插件欄位也是如此，有時候會出現，有時候消失。
是否有辦法讓此插件正常運作呢?
![1683071505216](https://user-images.githubusercontent.com/66938190/235809248-0055e07d-b260-4937-bc35-8b93cdcc6c1e.jpg)
![1683071538846](https://user-images.githubusercontent.com/66938190/235809263-6a866029-a58f-43b3-b479-261408e73074.jpg)

**Comment by lawvs** [comment]
根据截图显示，插件应该是崩溃了，能否打开开发者工具提供一下相关的崩溃日志，非常感谢

**Comment by darkwang2003** [comment]
> 根据截图显示，插件应该是崩溃了，能否打开开发者工具提供一下相关的崩溃日志，非常感谢

昨天已經用poi的插件修復，目前已經正常，下次再發生相同問題的時候再去撈日志，多謝。

**Comment by lawvs** [comment]
Unable to reproduce the issue, so I am closing it.
