### ISSUE TITLE
建议 任务搜索 可以通过 任务奖励的内容 来寻找未完成任务

### ISSUE THREAD

**Issue by AkatsukiZhang** [lawvs/poi-plugin-quest-2#40]
10周年回坑发现好多船改造需要各种特殊道具，比如战斗详报，查wiki检查任务是否完成相对比较麻烦，希望能通过任务奖励来搜索任务，这样比较方便！

**Comment by lawvs** [comment]
了解了，我会抽空实现这个功能

**Comment by lawvs** [comment]
我检查了一下，任务搜索一直是支持搜索 任务奖励 的，比如这是搜索 战斗详报 的结果，具体的实现细节是搜索任务描述之后匹配字符串

<img width="710" alt="Screenshot 2023-07-23 at 22 13 11" src="https://github.com/lawvs/poi-plugin-quest-2/assets/18554747/f35d045a-679e-4b53-883b-131fb5417929">

**Comment by AkatsukiZhang** [comment]
现在是可以搜索到任务了，之前没搜索到大概是我用的日文"戦闘詳報"搜索的任务吧。
当然，如果能有对 简中/繁中/日文 的道具名称自适应就好了(随口说说)
总之，感谢！
