### ISSUE TITLE
空白處增加任務需要的Lv艦娘是否存在的判斷提示

### ISSUE THREAD

**Issue by skysumbra** [lawvs/poi-plugin-quest-2#5]
**poi 版本 / poi version:**
10.6.0
**操作系统 / OS:**
WIN 10
**插件版本 / Plugin version:**
0.3.2
**功能的详细描述 / Details on the feature:**
目前任務所需艦娘多數會在任務敘述或是翻譯內提供，但是無法確認擁有該艦娘，如增加該持有的等級艦娘是否存在的判斷提示，可以快速判斷該任務是否可以執行

**Comment by lawvs** [comment]
感謝你的反饋，目前插件的信息源為第三方提供的文本數據，暫時沒有餘力對數據進行進一步的結構化處理和分析。
