### ISSUE TITLE
许多任务代号变更，希望及时进行前置后置任务的代号更新。

### ISSUE THREAD

**Issue by NorAOS** [lawvs/poi-plugin-quest-2#57]
**poi 版本 / poi version:**
10.9.2
**操作系统 / OS:**
Windows10
**插件版本 / Plugin version:**
0.10.1
**功能的详细描述 / Details on the feature:**
举例，任务Bm8的前置任务现在应为Cm1，但仍显示是C8（C8应该是Cm1“精锐舰队演习”任务的旧代号，现在不再使用）。这就导致查询Bm8时显示前置是C8，但C8是个已经不存在的任务代号，无法查询。
应该是因为这段时间wiki在做很多周期任务的更名导致了这个问题？如果不是您插件的问题请麻烦您反馈给wiki请他们更新数据源。

**Comment by lawvs** [comment]
非常感谢你的反馈，我已经将问题报告给上游了数据源

**Comment by lawvs** [comment]
已在 0.10.2 中修复，现在所有任务代号应该都是新代号了
