### ISSUE TITLE
任务完成状态推算有误

### ISSUE THREAD

**Issue by bgli100** [lawvs/poi-plugin-quest-2#83]
**poi 版本 / poi version:** 
10.9.2
**操作系统 / OS:**
Win 11 22H2
**插件版本 / Plugin version:**
0.11.0
**你遇到了什么样的问题 / The problem you've met:**
任务A8标注"状态未知"，其唯一前置A5标注“已完成”，唯一后置A17标注“状态未知”
都是初期编成任务，应不涉及定期任务的情况。
由于A8的全部前置（A5）推算是已完成，那么要么A8标已解锁（出现在任务列表里），要么标已完成（满足出现条件后仍未出现，说明已完成）

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
老号，相关任务早就做过了，进任务页面全翻一遍不影响上述问题出现

**Comment by lawvs** [comment]
你好，方便从设置界面导出你的任务数据吗，这有助于帮助我排查问题

![Screenshot 2023-12-15 at 23 46 11](https://github.com/lawvs/poi-plugin-quest-2/assets/18554747/7859430e-6fc0-4780-afdb-17e633e37c4a)

**Comment by bgli100** [comment]
[{"api_no":218,"api_category":2,"api_type":1,"api_label_type":2,"api_state":2,"api_title":"敵補給艦を3隻撃沈せよ！","api_detail":"艦隊を出撃させ、敵補給艦を捕捉、これを撃滅せよ！","api_voice_id":0,"api_get_material":[100,50,200,50],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":229,"api_category":2,"api_type":2,"api_label_type":3,"api_state":1,"api_title":"敵東方艦隊を撃滅せよ！","api_detail":"西方海域に出撃し、敵東方艦隊の主力を捕捉、これを撃滅せよ！","api_voice_id":0,"api_get_material":[400,0,0,700],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":256,"api_category":2,"api_type":3,"api_label_type":6,"api_state":1,"api_title":"「潜水艦隊」出撃せよ！","api_detail":"潜水艦戦力を中核とした艦隊で中部海域哨戒線へ反復出撃、敵戦力を漸減せよ！","api_voice_id":0,"api_get_material":[0,600,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":266,"api_category":2,"api_type":3,"api_label_type":6,"api_state":1,"api_title":"「水上反撃部隊」突入せよ！","api_detail":"駆逐艦を旗艦とした重巡1隻軽巡1隻駆逐艦4隻からなる水上挺身部隊、沖ノ島沖に突入せよ！","api_voice_id":0,"api_get_material":[0,600,0,200],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":280,"api_category":2,"api_type":3,"api_label_type":6,"api_state":1,"api_title":"兵站線確保！海上警備を強化実施せよ！","api_detail":"海上警備任務：軽空母または軽巡級1隻、駆逐艦または海防艦を計3隻以上配備した海上護衛艦隊で、<br>南西諸島沖警備、海上護衛作戦、南1号作戦、南西諸島哨戒を実施、各作戦海域の敵を撃滅せよ！","api_voice_id":0,"api_get_material":[400,400,0,400],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":302,"api_category":3,"api_type":2,"api_label_type":3,"api_state":1,"api_title":"大規模演習","api_detail":"今週中に「演習」で他の提督の艦隊に対して20回「勝利」しよう！","api_voice_id":0,"api_get_material":[200,200,200,200],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":304,"api_category":3,"api_type":1,"api_label_type":2,"api_state":1,"api_title":"「演習」で他提督を圧倒せよ！","api_detail":"本日中に他の司令官の艦隊との「演習」で5回以上「勝利」をおさめよう！","api_voice_id":0,"api_get_material":[0,50,0,50],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":330,"api_category":3,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"空母機動部隊、演習始め！","api_detail":"空母機動部隊演習任務：航空母艦旗艦他1隻計2隻以上及び駆逐艦2隻を含む空母機動部隊を編成。<br>機動部隊各艦の練度向上を図る！同艦隊で、本日中に演習で4回以上勝利せよ！","api_voice_id":0,"api_get_material":[0,400,0,400],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":339,"api_category":3,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"「十九駆」演習！","api_detail":"駆逐艦演習任務：第十九駆逐隊「磯波」「浦波」「綾波」「敷波」の4隻を含む演習艦隊を編成。<br>同艦隊で本日中に演習で【S判定】勝利3回以上を達成せよ！精鋭十九駆、じゃ、見ててよね！","api_voice_id":0,"api_get_material":[190,190,190,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":342,"api_category":3,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"小艦艇群演習強化任務","api_detail":"駆逐艦または海防艦計4隻(軽巡級1隻導入可能)を含む演習艦隊を編成、<br>同演習艦隊による演習で本日中に【A判定】以上の勝利を4回以上達成せよ！","api_voice_id":0,"api_get_material":[300,300,300,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":345,"api_category":3,"api_type":5,"api_label_type":110,"api_state":1,"api_title":"演習ティータイム！","api_detail":"「Warspite」「金剛」「Ark Royal」「Nelson」及びJ級駆逐艦から4隻以上含む艦隊を編成！<br>同ティータイム艦隊で、本日中に【A判定】以上の勝利を4回以上達成せよ！Tea Timeは大切ネー！","api_voice_id":0,"api_get_material":[0,600,600,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":346,"api_category":3,"api_type":5,"api_label_type":110,"api_state":1,"api_title":"最精鋭！主力オブ主力、演習開始！","api_detail":"第十駆逐隊演習任務：改装甲型駆逐艦「夕雲改二」「巻雲改二」「風雲改二」「秋雲改二」の4隻を<br>含む艦隊を編成、同駆逐隊を含む精鋭艦隊で、本日中に【S判定】以上の勝利を4回以上達成せよ！","api_voice_id":0,"api_get_material":[250,250,250,250],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":348,"api_category":3,"api_type":5,"api_label_type":102,"api_state":1,"api_title":"「精鋭軽巡」演習！","api_detail":"旗艦に軽巡級(雷巡を除く)、旗艦含む3隻以上の軽巡級と随伴駆逐艦2隻を配備した軽巡演習艦隊を<br>編成、同艦隊により本日中に演習で【A判定】以上の勝利を4回以上達成せよ！","api_voice_id":0,"api_get_material":[200,0,200,200],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":370,"api_category":3,"api_type":2,"api_label_type":3,"api_state":2,"api_title":"【Xmas限定】聖夜の海上護衛隊演習","api_detail":"「鹿島」「択捉」「松輪」「佐渡」「福江」「鵜来」「岸波」「早波」「谷風」「江風」「山雲」「朝雲」<br>「山汐丸」及び丁型海防艦のうち4隻以上を含む艦隊で、今週中に演習【A判定】以上を5回達成せよ！","api_voice_id":0,"api_get_material":[250,250,250,250],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":410,"api_category":4,"api_type":2,"api_label_type":3,"api_state":1,"api_title":"南方への輸送作戦を成功させよ！","api_detail":"激戦海域である南方海域への「東京急行」系遠征を敢行、これを成功させよ！","api_voice_id":0,"api_get_material":[150,0,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":426,"api_category":4,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"海上通商航路の警戒を厳とせよ！","api_detail":"遠征任務：遠征任務「警備任務」「対潜警戒任務」「海上護衛任務」「強行偵察任務」<br>を実施し、敵の通商破壊部隊を制圧、海上通商航路の安全を確保せよ！","api_voice_id":0,"api_get_material":[800,0,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":434,"api_category":4,"api_type":5,"api_label_type":102,"api_state":1,"api_title":"特設護衛船団司令部、活動開始！","api_detail":"海上護衛任務：遠征任務「警備任務」「海上護衛任務」「兵站強化任務」「海峡警備行動」<br>「タンカー護衛任務」の各任務を、海防艦・駆逐艦などを主軸とした護衛艦艇で実施せよ！","api_voice_id":0,"api_get_material":[1000,0,0,500],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":436,"api_category":4,"api_type":5,"api_label_type":103,"api_state":1,"api_title":"練習航海及び警備任務を実施せよ！","api_detail":"練習航海及び警備任務：「練習航海」「長距離練習航海」「警備任務」「対潜警戒任務」<br>「強行偵察任務」の各遠征任務を、軽巡・駆逐艦・海防艦などの艦艇で実施せよ！","api_voice_id":0,"api_get_material":[400,400,400,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":437,"api_category":4,"api_type":5,"api_label_type":105,"api_state":1,"api_title":"小笠原沖哨戒線の強化を実施せよ！","api_detail":"小笠原沖哨戒線任務：「対潜警戒任務」「小笠原沖哨戒線遠征」「小笠原沖戦闘哨戒」<br>「南西方面航空偵察作戦」の各遠征任務を軽巡・駆逐艦など実施、これを成功させよ！","api_voice_id":0,"api_get_material":[600,600,0,400],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":438,"api_category":4,"api_type":5,"api_label_type":108,"api_state":1,"api_title":"南西諸島方面の海上護衛を強化せよ！","api_detail":"海上護衛任務：「兵站強化任務」「対潜警戒任務」「タンカー護衛任務」及び<br>「南西諸島捜索撃滅戦」の各遠征任務を実施、これを成功させよ！","api_voice_id":0,"api_get_material":[2000,0,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":439,"api_category":4,"api_type":5,"api_label_type":109,"api_state":1,"api_title":"兵站強化遠征任務【基本作戦】","api_detail":"兵站強化遠征任務：「海上護衛任務」「兵站強化任務」「ボーキサイト輸送任務」及び<br>「南西方面航空偵察作戦」の各遠征任務を実施、これを成功させよ！","api_voice_id":0,"api_get_material":[0,0,480,480],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":444,"api_category":4,"api_type":5,"api_label_type":103,"api_state":1,"api_title":"新兵装開発資材輸送を船団護衛せよ！","api_detail":"新兵装開発資材輸送護衛：「海上護衛任務」「資源輸送任務」「タンカー護衛任務」<br>「南西方面航空偵察作戦」「ボーキサイト輸送任務」遠征を実施、これを成功させよ！","api_voice_id":0,"api_get_material":[1000,300,300,600],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":605,"api_category":6,"api_type":1,"api_label_type":2,"api_state":1,"api_title":"新装備「開発」指令","api_detail":"「工廠」で装備アイテムを新たに「開発」しよう(失敗もOK)！","api_voice_id":0,"api_get_material":[40,40,40,40],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":613,"api_category":6,"api_type":2,"api_label_type":3,"api_state":1,"api_title":"資源の再利用","api_detail":"「工廠」で余剰の装備アイテムをなるべく多く「廃棄」して、鋼材の再利用に努めよう！","api_voice_id":0,"api_get_material":[0,0,100,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":626,"api_category":6,"api_type":3,"api_label_type":6,"api_state":1,"api_title":"精鋭「艦戦」隊の新編成","api_detail":"要熟練搭乗員：練度max「零戦21型」搭載「鳳翔」秘書艦で「零戦21型」x2「九六艦戦」x1廃棄！","api_voice_id":0,"api_get_material":[0,0,0,50],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":628,"api_category":6,"api_type":3,"api_label_type":6,"api_state":1,"api_title":"機種転換","api_detail":"練度max「零戦21型(熟練)」搭載空母を秘書艦にして、新たに「零戦52型」を2つ廃棄！","api_voice_id":0,"api_get_material":[0,0,0,50],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":637,"api_category":6,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"「熟練搭乗員」養成","api_detail":"勲章x2消費：「鳳翔」秘書艦に練度max及び改修max「九六式艦戦」を搭載、熟練搭乗員を養成せよ！<br>(任務達成後、部隊は消滅します)","api_voice_id":0,"api_lost_badges":2,"api_get_material":[0,0,0,100],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":645,"api_category":6,"api_type":3,"api_label_type":6,"api_state":1,"api_title":"「洋上補給」物資の調達","api_detail":"「三式弾」一つを廃棄し、燃料750及び弾薬750と「ドラム缶(輸送用)」二つと「九一式徹甲弾」一つを<br>用意せよ！※任務達成後、用意した資源及び必要装備(徹甲弾は改修値の低いもの優先)は消滅します。","api_voice_id":0,"api_get_material":[0,0,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":654,"api_category":6,"api_type":5,"api_label_type":110,"api_state":1,"api_title":"精鋭複葉機飛行隊の編成","api_detail":"精鋭複葉機飛行隊の編成：秘書艦「Ark Royal」に改修max「Swordfish」を一番スロットに搭載、<br>「Swordfish」x1「Fulmar」x2を廃棄、「熟練搭乗員」、弾薬とボーキサイトを各1,500用意せよ！","api_voice_id":0,"api_get_material":[0,0,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":686,"api_category":6,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"戦時改修A型高角砲の量産","api_detail":"旗艦特型駆逐艦の第一スロに「12.7cm連装砲A型改二」改修maxを装備、 「10cm連装高角砲」x4<br> 「94式高射装置」x1を廃棄、開発資材x30、鋼材900、新型砲熕兵装資材x1を再び準備せよ！","api_voice_id":0,"api_get_material":[0,200,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":702,"api_category":7,"api_type":1,"api_label_type":2,"api_state":1,"api_title":"艦の「近代化改修」を実施せよ！","api_detail":"近代化改修を実施して、２回以上これを成功させよ！","api_voice_id":0,"api_get_material":[20,20,50,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":715,"api_category":7,"api_type":5,"api_label_type":111,"api_state":1,"api_title":"続：「駆逐艦」の改修工事を実施せよ！","api_detail":"近代化改修任務：鋼材900及びボーキサイト500を準備して、任意の駆逐艦を近代化改修！<br>[軽巡洋艦]x3隻同時使用により2回成功させよ！※任務達成後、準備資源は消費します。","api_voice_id":0,"api_get_material":[0,300,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":854,"api_category":8,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"戦果拡張任務！「Z作戦」前段作戦","api_detail":"戦果拡張作戦：我が第一艦隊に精鋭艦艇を集中配備、同精鋭艦隊を以て、南西諸島の沖ノ島海域、<br>中部海域哨戒線、グアノ環礁沖の敵艦隊を撃破、中部北海域ピーコック島の敵戦力を破砕殲滅せよ！","api_voice_id":0,"api_get_material":[0,2000,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":861,"api_category":8,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"強行輸送艦隊、抜錨！","api_detail":"航路護衛任務：航空戦艦(または補給艦でも可)2隻を中核とした艦隊で、鎮守府近海航路における<br>輸送船団護衛作戦を実施。同輸送護衛作戦を2回成功させよ！","api_voice_id":0,"api_get_material":[1000,400,400,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":873,"api_category":8,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"北方海域警備を実施せよ！","api_detail":"北方海域警備任務：北方海域の警備を実施する。軽巡を1隻以上含む艦隊で、北方海域モーレイ海、<br>キス島沖、アルフォンシーノ方面に艦隊を展開、北方海域方面の警備と制海権確保に努めよ！","api_voice_id":0,"api_get_material":[500,500,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":888,"api_category":8,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"新編成「三川艦隊」、鉄底海峡に突入せよ！","api_detail":"鉄底海峡戦果拡張：「鳥海」「青葉」「衣笠」「加古」「古鷹」「天龍」「夕張」の中から4隻を含む突入<br>艦隊を編成。南方海域前面及びサブ島沖海域、サーモン海域に突入、敵艦隊を撃滅せよ！","api_voice_id":0,"api_get_material":[800,800,800,800],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":893,"api_category":8,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"泊地周辺海域の安全確保を徹底せよ！","api_detail":"泊地近海警戒戦果拡張：有力な泊地哨戒部隊を編成、鎮守府近海、ブルネイ泊地沖、タウイタウイ泊地沖<br>に反復出撃！各周辺海域に出没する敵潜を制圧、さらに泊地周辺の脅威となる敵戦力を捕捉撃滅せよ！","api_voice_id":0,"api_get_material":[2000,500,0,500],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":894,"api_category":8,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"空母戦力の投入による兵站線戦闘哨戒","api_detail":"空母を含む有力な哨戒艦隊を編成、製油所地帯沿岸、南西諸島防衛線、南西諸島近海、バシー海峡<br>及び東部オリョール海を戦闘哨戒、各海域の敵艦隊を捕捉撃滅、各海域兵站線の安全を確保せよ！","api_voice_id":0,"api_get_material":[600,0,600,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":903,"api_category":9,"api_type":5,"api_label_type":7,"api_state":1,"api_title":"拡張「六水戦」、最前線へ！","api_detail":"軽巡「夕張改二」型の旗艦に随伴第六水雷戦隊駆逐艦2隻以上または「由良改二」を含む艦隊で、南方海域<br>前面、南方サーモン海域、中部北海域ピーコック島沖、中部KW環礁沖海域に展開、敵戦力を撃滅せよ！","api_voice_id":0,"api_get_material":[0,1000,1000,1000],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":904,"api_category":9,"api_type":5,"api_label_type":102,"api_state":1,"api_title":"精鋭「十九駆」、躍り出る！","api_detail":"改装特II型駆逐艦「綾波改二」及び同「敷波改二」を含む精鋭艦隊を前線に投入、南西諸島海域沖ノ島沖、<br>北方海域全域、西方海域カレー洋リランカ島沖、南方サブ島沖海域に展開、各敵主力を捕捉撃滅せよ！","api_voice_id":0,"api_get_material":[1900,0,1900,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":905,"api_category":9,"api_type":5,"api_label_type":102,"api_state":1,"api_title":"「海防艦」、海を護る！","api_detail":"海防艦3隻を含む5隻以下の海上護衛隊を、鎮守府海域に展開。鎮守府正面海域、南西諸島沖海域、製油所<br>地帯沿岸、鎮守府近海、鎮守府近海航路の各海域の安全確保と対潜掃蕩を図れ！海防艦戦隊、抜錨せよ！","api_voice_id":0,"api_get_material":[1200,600,600,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":912,"api_category":9,"api_type":5,"api_label_type":103,"api_state":1,"api_title":"工作艦「明石」護衛任務","api_detail":"工作艦護衛任務：旗艦に工作艦「明石」、護衛の駆逐艦3隻以上で製油所地帯沿岸、鎮守府近海航路、<br>南西諸島近海、バシー海峡、東部オリョール海に展開。「明石」を護衛、同海域での作戦を成功させよ！","api_voice_id":0,"api_get_material":[600,0,600,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":928,"api_category":9,"api_type":5,"api_label_type":109,"api_state":1,"api_title":"歴戦「第十方面艦隊」、全力出撃！","api_detail":"重巡「羽黒」「足柄」「妙高」「高雄」、駆逐艦「神風」のうち2隻以上を含む精強な艦隊を編成！<br>マラッカ海峡ペナン島沖深部、タウイタウイ泊地沖深部、西方カレー洋海域に反復出撃！敵を撃滅せよ！","api_voice_id":0,"api_get_material":[1000,1000,1000,1000],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":973,"api_category":9,"api_type":5,"api_label_type":105,"api_state":1,"api_title":"日英米合同水上艦隊、抜錨せよ！","api_detail":"米英艦艇3隻以上を含む空母を伴わない艦隊で、北方海域モーレイ海及びアルフォンシーノ方面、<br>西方海域リランカ島、南西海域ペナン島沖深部を哨戒、敵戦力を捕捉、これを撃破せよ！","api_voice_id":0,"api_get_material":[350,450,350,550],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":975,"api_category":9,"api_type":5,"api_label_type":105,"api_state":1,"api_title":"精鋭「第十九駆逐隊」、全力出撃！","api_detail":"精鋭第十九駆逐隊「磯波改二」「浦波改二」「綾波改二」「敷波改二」を含む艦隊で、鎮守府近海、<br>南西諸島東部オリョール海、北方キス島沖、南方サブ島沖海域に出撃！敵艦隊を捕捉撃滅せよ！","api_voice_id":0,"api_get_material":[190,190,190,190],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":1103,"api_category":11,"api_type":5,"api_label_type":106,"api_state":1,"api_title":"潜水艦強化兵装の量産","api_detail":"「61cm三連装(酸素)魚雷」x3廃棄、開発資材x60と「九三式水中聴音機」「13号対空電探改」各x2を<br>準備せよ！　※任務達成後、用意した開発資材及び必要装備(低改修値のもの優先)は消費します。","api_voice_id":0,"api_get_material":[0,100,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":1111,"api_category":11,"api_type":4,"api_label_type":1,"api_state":1,"api_title":"精鋭「一式陸攻」隊の編成","api_detail":"精鋭陸攻隊の編成：野中隊長率いる精鋭陸攻隊の編成を行う！「一式陸攻 二二型甲」(最大改修)x1、<br>さらに「一式陸攻」x2、熟練搭乗員x3を準備せよ！(任務達成後、用意した必要装備は消滅します)","api_voice_id":0,"api_get_material":[0,0,0,300],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":1123,"api_category":11,"api_type":5,"api_label_type":101,"api_state":1,"api_title":"改良三座水上偵察機の増備","api_detail":"旗艦「利根改二」または「由良改二」第一スロに最大改修「零式水上偵察機」。「九七式艦攻(九三一空)」<br>x2廃棄、ボーキ950、新型航空兵装資材x2、開発資材x35、熟練搭乗員x2を準備！","api_voice_id":0,"api_get_material":[0,0,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0},{"api_no":1134,"api_category":11,"api_type":4,"api_label_type":1,"api_state":1,"api_title":"22号対水上電探の改良","api_detail":"旗艦「時雨改二/改三」または「満潮改二」第一装備スロに「22号対水上電探改四(★max)」を<br>装備。開発資材x22、新型兵装資材x2、「22号対水上電探」x4、改修資材x6を準備せよ！","api_voice_id":0,"api_get_material":[0,0,0,0],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0}]

**Comment by lawvs** [comment]
非常感谢你的配合，经过排查后发现出现这个问题的原因是 涉及 A8 的这条任务链已经完全被完成了。因为最终任务 B120 精鋭「二七駆」第一小队、出击せよ！ 没有其他后置任务导致程序不知道 B120 已经完成，进而标记了给整个任务链标记了状态未知。

我会抽空更新任务依赖的检查算法，再次感谢你提供的数据！

**Comment by lawvs** [comment]
我已经修复了这个问题，在更新到`v0.12.0`之后你的数据中很多已经完成的任务链都将被标记为已完成，比如

- B112 - 精锐 “四水战”，在南方海域展开吧！ 及其前置
- B136 - 精锐 “第二十四驱逐队” 出击！ 及其前置
- F121 - 逆探以及改良水上电探的实战配备 及其前置
- 2307B2 - 主力 of 主力，拔锚！歼灭敌方舰队！ 及其前置

我认为可能存在由于数据不准确将任务标记为已完成的情况，如果有发现标记不正确的情况欢迎随时反馈

Fixed in https://github.com/lawvs/poi-plugin-quest-2/commit/9e468a5a855765e0c50b4ff69d658ded9c70a292
