### ISSUE TITLE
希望能在插件里查看任务的前置和后续

### ISSUE THREAD

**Issue by KIrayamoto** [lawvs/poi-plugin-quest-2#9]
**poi 版本 / poi version:10.7**

**操作系统 / OS:Win10**

**插件版本 / Plugin version:0.5.5**

**功能的详细描述 / Details on the feature:以前旧版的任务信息是可以查看任务的前置和后续的，新版的似乎没这个功能？**

**Comment by lawvs** [comment]
这个功能还在计划中，目前计划在年内完成！

非常感谢你的反馈！
